version: "3.1"
services:
  app:
    build: .
    image: dbwebapp_image
    container_name: dbwebapp
    restart: unless-stopped
    working_dir: /app/backend
    command: npm run start
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/helpdesk
    # volumes:
    #   - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  pooling-process:
    build: .
    image: dbwebapp_image
    container_name: pooling
    restart: unless-stopped
    working_dir: /app/backend
    command: npm run pooling
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/helpdesk
    # volumes:
    #   - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
