# version: "2"
# services:
#   testedocker:
#     build: .
#     environment:
#       - MONGO_DATA_DIR=/data/db
#       - MONGO_LOG_DIR=/dev/null
#     volumes:
#       - ./data/db:/data/db
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo
#     ports:
#       - 27017:27017
#     command: mongod --smallfiles --logpath=/dev/null # --quiet

version: "3"
services:
  app:
    image: progweb
    build: .
    restart: always
    ports:
      - "80:3000"
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017/cities
      - NODE_ENV=production
      - API_BASE_URL=http://127.0.0.1:80/v1/teste
      - PORT=3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=root
    # - MONGO_INITDB_ROOT_PASSWORD=pass
    # - MONGO_INITDB_DATABASE=cities
    volumes:
      - ./data/mongodb:/data/db
